name: 'Size Compare'
description: 'Compare size of the built assets'
branding:
  icon: bar-chart-2
  color: blue
inputs:
  gist-id:
    description: Id of the GIST to save size to
    required: true
  token:
    description: A personal access token with "gist" and "repo" permissions. Should be stored as a Secret.
    required: true
  bundle-directory:
    description: Files' directory compare size for
    required: true
  main-branch:
    description: Name of the main branch to compare with
    default: 'main'
  include:
    description: If passed use this value as a glob pattern to filter files from "bundle-directory"
    required: false
  exclude:
    description: A glob pattern to filter out files filtered by "include" from "bundle-directory"
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'node16'
  main: 'dist/index.js'
